### ISSUE TITLE
支持 Marvel Unlimited

### ISSUE THREAD

**Issue by bowbahdoe** [Hentioe/mikack-cli#11]

**Comment by Hentioe** [comment]
我初步判断这个网站并不能支持游客在线阅读，所以不能适合这个程序。如果有途径请告知。

**Comment by bowbahdoe** [comment]
他们的网站确实有一种通读网页的方法，尽管它不像许多漫画网站那样简单明了，并且确实需要登录，所以出于此目的，这可能是不合理的工作量，这是有道理的。工具。
