### ISSUE TITLE
windows版教程不全

### ISSUE THREAD

**Issue by c4yg70** [Hentioe/mikack-cli#13]
请问各个不同的工作模式有何不同，如何切换输出格式？
默认的模式是下载图片并保存到对应文件夹后进行压缩，输出后对应文件夹没有删除，不知是bug还是没有删除。
平台 surface laptop一代，win10版本1809.17763.316，除firefox和火绒外无其它后台程序，下载https://manhua.dmzj.com/qsgsjdbdsn/，模式1，范围1-75

**Comment by c4yg70** [comment]
另：每个任务的对应文件夹和zip均包含了trace.json，是否可以在输出时忽略/删除？

**Comment by Hentioe** [comment]
1. 不同的工作模式是在 Windows 上特有的，在其它系统没有。因为考虑到 Windows 用户不一定都懂命令行的使用。之后会给 Windows 添加更多的交互选项。
2. `trace.json` 这个文件记录了所有图片的来源。后续会让包含 `trace.json` 变得可选
