### ISSUE TITLE
Mac下epub没有目录生成

### ISSUE THREAD

**Issue by oatiz** [Hentioe/mikack-cli#14]
git clone项目后 build. 执行:

manga -f epub -o ~/Downloads/ https://manhua.dmzj.com/oumushexueximanhua/

生成的epub 没有目录

**Comment by Hentioe** [comment]
-o 仅仅指定 epub 文件的输出目录。下载的原始图片在 manga_res/[漫画名] 目录中

**Comment by oatiz** [comment]
![IMG_0786](https://user-images.githubusercontent.com/24953151/54750042-67bb6480-4c11-11e9-8e96-5eddd269f71d.JPG)

偶的意思是 生成的漫画 木有 目录章节  难受

**Comment by Hentioe** [comment]
但是漫画不就是一张张图片吗？所以目录就是 1P 2P 3P  这样子，你想说的目录章节是什么意思？

**Comment by oatiz** [comment]
哦,明白了, 我的问题

**Comment by Hentioe** [comment]
好的，那我关了。
