### ISSUE TITLE
error[E0554]: #![feature] may not be used on the stable release channel

### ISSUE THREAD

**Issue by xljeff** [Hentioe/mikack-cli#17]
CentOS 7
cargo build 錯誤訊息 , 感謝協助

[root@rd-studio manga]# cargo run
  Downloaded either v1.5.3
  Downloaded hyper v0.12.35
   Compiling proc-macro2 v1.0.3
   Compiling semver-parser v0.7.0
   Compiling libc v0.2.62
   Compiling autocfg v0.1.6
   Compiling unicode-xid v0.2.0
   Compiling rand_core v0.4.2
   Compiling syn v1.0.5
   Compiling byteorder v1.3.2
   Compiling proc-macro2 v0.4.30
   Compiling siphasher v0.2.3
   Compiling stable_deref_trait v1.1.1
   Compiling unicode-xid v0.1.0
   Compiling arrayvec v0.4.11
   Compiling log v0.4.8
   Compiling cc v1.0.45
   Compiling smallvec v0.6.10
   Compiling serde v1.0.100
   Compiling lazy_static v1.4.0
   Compiling ryu v1.0.0
   Compiling nodrop v0.1.13
   Compiling cfg-if v0.1.9
   Compiling scopeguard v0.3.3
   Compiling either v1.5.3
   Compiling string_cache_shared v0.3.0
   Compiling pkg-config v0.3.16
   Compiling scopeguard v1.0.0
   Compiling memchr v2.2.1
   Compiling futures v0.1.29
   Compiling slab v0.4.2
   Compiling syn v0.15.44
   Compiling fnv v1.0.6
   Compiling version_check v0.1.5
   Compiling itoa v0.4.4
   Compiling bitflags v1.1.0
   Compiling matches v0.1.8
   Compiling ucd-trie v0.1.2
   Compiling foreign-types-shared v0.1.1
   Compiling mac v0.1.1
   Compiling new_debug_unreachable v1.0.3
   Compiling httparse v1.3.4
   Compiling rustc-demangle v0.1.16
   Compiling failure_derive v0.1.5
   Compiling openssl v0.10.24
   Compiling maplit v1.0.2
   Compiling try-lock v0.2.2
   Compiling unic-char-range v0.7.0
   Compiling unic-common v0.7.0
   Compiling regex-syntax v0.6.12
   Compiling percent-encoding v1.0.1
   Compiling crc32fast v1.2.0
   Compiling dtoa v0.4.4
   Compiling indexmap v1.2.0
   Compiling native-tls v0.2.3
   Compiling percent-encoding v2.1.0
   Compiling precomputed-hash v0.1.1
   Compiling utf-8 v0.7.5
   Compiling procedural-masquerade v0.1.6
   Compiling encoding_rs v0.8.19
   Compiling cgmath v0.16.1
   Compiling winapi v0.3.8
   Compiling openssl-probe v0.1.2
   Compiling adler32 v1.0.3
   Compiling deunicode v0.4.3
   Compiling approx v0.1.1
   Compiling unicode-width v0.1.6
   Compiling thin-slice v0.1.1
   Compiling mime v0.3.14
   Compiling ordermap v0.3.5
   Compiling fixedbitset v0.1.9
   Compiling humansize v1.1.0
   Compiling podio v0.1.6
   Compiling quick-error v1.2.2
   Compiling glob v0.2.11
   Compiling rgb v0.8.14
   Compiling ego-tree v0.6.0
   Compiling lazy_static v0.2.11
   Compiling same-file v1.0.5
   Compiling nom v2.2.1
   Compiling strsim v0.8.0
   Compiling ansi_term v0.11.0
   Compiling vec_map v0.8.1
   Compiling termcolor v1.0.5
   Compiling semver v0.9.0
   Compiling rand_pcg v0.1.2
   Compiling rand_chacha v0.1.1
   Compiling rand v0.6.5
   Compiling num-traits v0.2.8
   Compiling num-integer v0.1.41
   Compiling rand_core v0.3.1
   Compiling rand_jitter v0.1.4
   Compiling phf_shared v0.7.24
   Compiling owning_ref v0.4.0
   Compiling owning_ref v0.3.3
   Compiling backtrace-sys v0.1.31
   Compiling bzip2-sys v0.1.7
   Compiling unicode-normalization v0.1.8
   Compiling thread_local v0.3.6
   Compiling servo_arc v0.1.1
   Compiling crossbeam-utils v0.6.6
   Compiling try_from v0.3.2
   Compiling openssl-sys v0.9.49
   Compiling lock_api v0.3.1
   Compiling tokio-sync v0.1.6
   Compiling unicase v2.5.1
   Compiling error-chain v0.12.1
   Compiling unicode-bidi v0.3.4
   Compiling pest v2.1.2
   Compiling foreign-types v0.3.2
   Compiling futf v0.1.4
   Compiling unic-char-property v0.7.0
   Compiling unic-ucd-version v0.7.0
   Compiling dtoa-short v0.3.2
   Compiling miniz_oxide v0.3.2
   Compiling slug v0.1.4
   Compiling getopts v0.2.21
   Compiling textwrap v0.11.0
   Compiling petgraph v0.4.13
   Compiling humantime v1.3.0
   Compiling scan_dir v0.3.3
   Compiling walkdir v2.2.9
   Compiling rustc_version v0.2.3
   Compiling rand_xorshift v0.1.1
   Compiling rand_isaac v0.1.1
   Compiling rand_hc v0.1.0
   Compiling phf v0.7.24
   Compiling lock_api v0.1.5
   Compiling tokio-executor v0.1.8
   Compiling crossbeam-queue v0.1.2
   Compiling idna v0.2.0
   Compiling idna v0.1.5
   Compiling pest_meta v2.1.2
   Compiling tendril v0.4.1
   Compiling unic-ucd-segment v0.7.0
   Compiling quote v1.0.2
   Compiling memoffset v0.5.1
   Compiling parking_lot_core v0.4.0
   Compiling parking_lot_core v0.6.2
   Compiling hyper v0.12.35
   Compiling parking_lot v0.9.0
   Compiling rand_os v0.1.3
   Compiling iovec v0.1.2
   Compiling net2 v0.2.33
   Compiling num_cpus v1.10.1
   Compiling time v0.1.42
   Compiling rand v0.4.6
   Compiling clicolors-control v1.0.1
   Compiling termios v0.3.1
   Compiling atty v0.2.13
   Compiling fxhash v0.2.1
   Compiling base64 v0.10.1
   Compiling quote v0.6.13
   Compiling want v0.2.0
   Compiling tokio-timer v0.2.11
   Compiling tokio-current-thread v0.1.6
   Compiling aho-corasick v0.7.6
   Compiling url v2.1.0
   Compiling url v1.7.2
   Compiling unic-segment v0.7.0
   Compiling flate2 v1.0.11
   Compiling bytes v0.4.12
   Compiling mio v0.6.19
   Compiling futures-cpupool v0.1.8
   Compiling parking_lot_core v0.2.14
   Compiling clap v2.33.0
   Compiling num-traits v0.1.43
   Compiling number_prefix v0.2.8
   Compiling syn v0.14.9
   Compiling backtrace v0.3.37
   Compiling bzip2 v0.3.3
   Compiling regex v1.3.1
   Compiling mime_guess v2.0.1
   Compiling cookie v0.12.0
   Compiling serde_derive v1.0.100
   Compiling pest_generator v2.1.1
   Compiling tokio-io v0.1.12
   Compiling string v0.2.1
   Compiling http v0.1.18
   Compiling tokio-buf v0.1.1
   Compiling parking_lot v0.4.8
   Compiling phf_generator v0.7.24
   Compiling uuid v0.7.4
   Compiling chrono v0.4.9
   Compiling cssparser v0.24.1
   Compiling synstructure v0.10.2
   Compiling html5ever v0.22.5
   Compiling zip v0.5.3
   Compiling console v0.9.0
   Compiling env_logger v0.6.2
   Compiling pest_derive v2.1.0
   Compiling crossbeam-epoch v0.7.2
   Compiling h2 v0.1.26
   Compiling http-body v0.1.0
   Compiling tree_magic v0.2.1
   Compiling parking_lot v0.7.1
   Compiling string_cache_codegen v0.4.2
   Compiling phf_codegen v0.7.24
   Compiling winconsole v0.10.0
   Compiling publicsuffix v1.5.3
   Compiling serde_json v1.0.40
   Compiling serde_urlencoded v0.5.5
   Compiling crossbeam-deque v0.7.1
   Compiling indicatif v0.11.0
   Compiling console v0.7.7
   Compiling tokio-reactor v0.1.9
   Compiling string_cache v0.7.3
   Compiling cssparser-macros v0.3.6
   Compiling selectors v0.20.0
   Compiling colored v1.8.0
   Compiling failure v0.1.5
   Compiling markup5ever v0.7.5
   Compiling tera v0.11.20
   Compiling tokio-threadpool v0.1.15
   Compiling tokio-tcp v0.1.3
warning[E0506]: cannot assign to `self.input.cached_token` because it is borrowed
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cssparser-0.24.1/src/parser.rs:572:17
    |
547 |     pub fn next_including_whitespace_and_comments(&mut self) -> Result<&Token<'i>, BasicParseError<'i>> {
    |                                                   - let's call the lifetime of this reference `'1`
...
560 |             Some(ref cached_token)
    |                  ---------------- borrow of `self.input.cached_token` occurs here
...
572 |                 self.input.cached_token = Some(CachedToken {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^ assignment to borrowed `self.input.cached_token` occurs here
...
584 |         Ok(token)
    |         --------- returning this value requires that `self.input.cached_token.0` is borrowed for `'1`
    |
    = warning: this error has been downgraded to a warning for backwards compatibility with previous releases
    = warning: this represents potential undefined behavior in your code and this warning will become a hard error in the future
    = note: for more information, try `rustc --explain E0729`

   Compiling cookie_store v0.7.0
   Compiling tokio v0.1.22
   Compiling hyper-tls v0.3.2
   Compiling reqwest v0.9.20
   Compiling scraper v0.9.2
   Compiling manga-bot v0.1.9 (https://github.com/manga-project/manga-bot?tag=0.1.9#a566abb5)
error[E0554]: #![feature] may not be used on the stable release channel
 --> /root/.cargo/git/checkouts/manga-bot-7b6d0cbc6e15c856/a566abb/src/lib.rs:1:1
  |
1 | #![feature(fn_traits)]
  | ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `manga-bot`.

To learn more, run the command again with --verbose.
`

**Comment by xljeff** [comment]
Rust 改為 rustup 安裝後, 錯誤訊息變更為

'[root@rd-studio manga]# ~/.cargo/bin/cargo build
   Compiling proc-macro2 v1.0.3
   Compiling autocfg v0.1.6
   Compiling semver-parser v0.7.0
   Compiling libc v0.2.62
   Compiling unicode-xid v0.2.0
   Compiling rand_core v0.4.2
   Compiling proc-macro2 v0.4.30
   Compiling byteorder v1.3.2
   Compiling syn v1.0.5
   Compiling siphasher v0.2.3
   Compiling log v0.4.8
   Compiling unicode-xid v0.1.0
   Compiling arrayvec v0.4.11
   Compiling stable_deref_trait v1.1.1
   Compiling lazy_static v1.4.0
   Compiling scopeguard v0.3.3
   Compiling cc v1.0.45
   Compiling nodrop v0.1.13
   Compiling either v1.5.3
   Compiling smallvec v0.6.10
   Compiling ryu v1.0.0
   Compiling serde v1.0.100
   Compiling cfg-if v0.1.9
   Compiling syn v0.15.44
   Compiling scopeguard v1.0.0
   Compiling pkg-config v0.3.16
   Compiling memchr v2.2.1
   Compiling fnv v1.0.6
   Compiling futures v0.1.29
   Compiling string_cache_shared v0.3.0
   Compiling slab v0.4.2
   Compiling version_check v0.1.5
   Compiling bitflags v1.1.0
   Compiling matches v0.1.8
   Compiling itoa v0.4.4
   Compiling rustc-demangle v0.1.16
   Compiling mac v0.1.1
   Compiling openssl v0.10.24
   Compiling httparse v1.3.4
   Compiling foreign-types-shared v0.1.1
   Compiling ucd-trie v0.1.2
   Compiling failure_derive v0.1.5
   Compiling new_debug_unreachable v1.0.3
   Compiling try-lock v0.2.2
   Compiling percent-encoding v2.1.0
   Compiling regex-syntax v0.6.12
   Compiling percent-encoding v1.0.1
   Compiling native-tls v0.2.3
   Compiling procedural-masquerade v0.1.6
   Compiling utf-8 v0.7.5
   Compiling dtoa v0.4.4
   Compiling crc32fast v1.2.0
   Compiling indexmap v1.2.0
   Compiling unic-common v0.7.0
   Compiling precomputed-hash v0.1.1
   Compiling unic-char-range v0.7.0
   Compiling maplit v1.0.2
   Compiling encoding_rs v0.8.19
   Compiling winapi v0.3.8
   Compiling cgmath v0.16.1
   Compiling openssl-probe v0.1.2
   Compiling adler32 v1.0.3
   Compiling thin-slice v0.1.1
   Compiling approx v0.1.1
   Compiling mime v0.3.14
   Compiling unicode-width v0.1.6
   Compiling fixedbitset v0.1.9
   Compiling ordermap v0.3.5
   Compiling deunicode v0.4.3
   Compiling same-file v1.0.5
   Compiling humansize v1.1.0
   Compiling rgb v0.8.14
   Compiling lazy_static v0.2.11
   Compiling ego-tree v0.6.0
   Compiling glob v0.2.11
   Compiling podio v0.1.6
   Compiling quick-error v1.2.2
   Compiling nom v2.2.1
   Compiling vec_map v0.8.1
   Compiling ansi_term v0.11.0
   Compiling termcolor v1.0.5
   Compiling strsim v0.8.0
   Compiling rand_pcg v0.1.2
   Compiling rand_chacha v0.1.1
   Compiling rand v0.6.5
   Compiling num-traits v0.2.8
   Compiling num-integer v0.1.41
   Compiling semver v0.9.0
   Compiling rand_core v0.3.1
   Compiling rand_jitter v0.1.4
   Compiling phf_shared v0.7.24
   Compiling owning_ref v0.4.0
   Compiling owning_ref v0.3.3
   Compiling thread_local v0.3.6
   Compiling backtrace-sys v0.1.31
   Compiling bzip2-sys v0.1.7
   Compiling servo_arc v0.1.1
   Compiling unicode-normalization v0.1.8
   Compiling crossbeam-utils v0.6.6
   Compiling try_from v0.3.2
   Compiling lock_api v0.3.1
   Compiling openssl-sys v0.9.49
   Compiling tokio-sync v0.1.6
   Compiling unicase v2.5.1
   Compiling error-chain v0.12.1
   Compiling unicode-bidi v0.3.4
   Compiling foreign-types v0.3.2
   Compiling pest v2.1.2
   Compiling futf v0.1.4
   Compiling dtoa-short v0.3.2
   Compiling unic-ucd-version v0.7.0
   Compiling unic-char-property v0.7.0
   Compiling miniz_oxide v0.3.2
   Compiling getopts v0.2.21
   Compiling textwrap v0.11.0
   Compiling petgraph v0.4.13
   Compiling slug v0.1.4
   Compiling walkdir v2.2.9
   Compiling humantime v1.3.0
   Compiling scan_dir v0.3.3
   Compiling rustc_version v0.2.3
   Compiling rand_xorshift v0.1.1
   Compiling rand_isaac v0.1.1
   Compiling rand_hc v0.1.0
   Compiling phf v0.7.24
   Compiling lock_api v0.1.5
   Compiling tokio-executor v0.1.8
   Compiling crossbeam-queue v0.1.2
   Compiling idna v0.1.5
   Compiling idna v0.2.0
   Compiling pest_meta v2.1.2
   Compiling tendril v0.4.1
   Compiling unic-ucd-segment v0.7.0
   Compiling quote v1.0.2
   Compiling parking_lot_core v0.4.0
   Compiling memoffset v0.5.1
   Compiling hyper v0.12.35
   Compiling parking_lot_core v0.6.2
   Compiling parking_lot v0.9.0
   Compiling rand_os v0.1.3
   Compiling iovec v0.1.2
   Compiling net2 v0.2.33
   Compiling num_cpus v1.10.1
   Compiling time v0.1.42
   Compiling rand v0.4.6
   Compiling termios v0.3.1
   Compiling clicolors-control v1.0.1
   Compiling atty v0.2.13
   Compiling quote v0.6.13
   Compiling fxhash v0.2.1
   Compiling base64 v0.10.1
   Compiling want v0.2.0
   Compiling tokio-current-thread v0.1.6
   Compiling tokio-timer v0.2.11
   Compiling aho-corasick v0.7.6
   Compiling url v1.7.2
   Compiling url v2.1.0
   Compiling flate2 v1.0.11
   Compiling unic-segment v0.7.0
   Compiling num-traits v0.1.43
   Compiling number_prefix v0.2.8
   Compiling bytes v0.4.12
   Compiling mio v0.6.19
   Compiling futures-cpupool v0.1.8
   Compiling parking_lot_core v0.2.14
   Compiling clap v2.33.0
   Compiling syn v0.14.9
   Compiling backtrace v0.3.37
   Compiling bzip2 v0.3.3
   Compiling regex v1.3.1
   Compiling mime_guess v2.0.1
   Compiling cookie v0.12.0
   Compiling pest_generator v2.1.1
   Compiling serde_derive v1.0.100
   Compiling chrono v0.4.9
   Compiling phf_generator v0.7.24
   Compiling uuid v0.7.4
   Compiling tokio-io v0.1.12
   Compiling tokio-buf v0.1.1
   Compiling string v0.2.1
   Compiling http v0.1.18
   Compiling parking_lot v0.4.8
   Compiling synstructure v0.10.2
   Compiling html5ever v0.22.5
   Compiling cssparser v0.24.1
   Compiling zip v0.5.3
   Compiling console v0.9.0
   Compiling env_logger v0.6.2
   Compiling pest_derive v2.1.0
   Compiling winconsole v0.10.0
   Compiling crossbeam-epoch v0.7.2
   Compiling parking_lot v0.7.1
   Compiling string_cache_codegen v0.4.2
   Compiling phf_codegen v0.7.24
   Compiling http-body v0.1.0
   Compiling h2 v0.1.26
   Compiling tree_magic v0.2.1
   Compiling publicsuffix v1.5.3
   Compiling serde_json v1.0.40
   Compiling serde_urlencoded v0.5.5
   Compiling colored v1.8.0
   Compiling crossbeam-deque v0.7.1
   Compiling indicatif v0.11.0
   Compiling console v0.7.7
   Compiling tokio-reactor v0.1.9
   Compiling string_cache v0.7.3
   Compiling selectors v0.20.0
   Compiling cssparser-macros v0.3.6
   Compiling failure v0.1.5
   Compiling tera v0.11.20
   Compiling markup5ever v0.7.5
   Compiling tokio-threadpool v0.1.15
   Compiling tokio-tcp v0.1.3
error[E0506]: cannot assign to `self.input.cached_token` because it is borrowed
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cssparser-0.24.1/src/parser.rs:572:17
    |
547 |     pub fn next_including_whitespace_and_comments(&mut self) -> Result<&Token<'i>, BasicParseError<'i>> {
    |                                                   - let's call the lifetime of this reference `'1`
...
560 |             Some(ref cached_token)
    |                  ---------------- borrow of `self.input.cached_token` occurs here
...
572 |                 self.input.cached_token = Some(CachedToken {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^ assignment to borrowed `self.input.cached_token` occurs here
...
584 |         Ok(token)
    |         --------- returning this value requires that `self.input.cached_token.0` is borrowed for `'1`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0506`.
error: Could not compile `cssparser`.

To learn more, run the command again with --verbose.
'

**Comment by Hentioe** [comment]
很久了，过来回复下：

本项目已经彻底重构，可以在 stable 版本的编译器上构建。推荐你继续常识最新的代码，远比之前要强大。
